### ISSUE TITLE
glitches

### ISSUE THREAD

**Issue by simple-github** [bastiaanbiester/AutoAccept#2]
the bot works like charm if the lobby leader uses it(all functions works) but if someone other than a lobby leader uses the bot,it clicks the menu button but doesn't click on the accept button.can you please fix that issue.
waiting for your reply :)

**Comment by simple-github** [comment]
also can you make the bot work only if the lobby is full,like it wont do anything(stay idle) if i am solo queing or the lobby just has 4 guys,if the lobby has 5 guys it can become active and start the queing process.

**Comment by bastiaanbiester** [comment]
Hi, sorry for the late reply. I have not used the tool recently, so I was not aware of these issues. I will look into them this week.

**Comment by simple-github** [comment]
np bro,thanks for replying, also can you make the bot work only if the lobby is full,like it wont do anything(stay idle) if i am solo queing or the lobby just has 4 guys,if the lobby has 5 guys it can become active and start the queing process.
plzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz :)

**Comment by bastiaanbiester** [comment]
I just released a new version (1.1.0) that should fix one of your issues:
> if someone other than a lobby leader uses the bot, it doesn't click on the accept button.

It works in my testing. You should also try running the tool as administrator.
If it still does not work I probably won't be able to help you any further.

**Comment by simple-github** [comment]
Please make it so that it only starts when the lobby is full plzzzzzzzzzz

**Comment by bastiaanbiester** [comment]
Then add it yourself. The source code is right here.
